// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SysEventosReTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sysEventosRe() {
    // Test name: SysEventosRe
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:8080/");
    // 2 | setWindowSize | 1936x1048 | 
    driver.manage().window().setSize(new Dimension(1936, 1048));
    // 3 | click | css=.field:nth-child(1) .input | 
    driver.findElement(By.cssSelector(".field:nth-child(1) .input")).click();
    // 4 | type | css=.field:nth-child(1) .input | davidmp@upeu.edu.pe
    driver.findElement(By.cssSelector(".field:nth-child(1) .input")).sendKeys("davidmp@upeu.edu.pe");
    // 5 | click | css=.field:nth-child(2) .input | 
    driver.findElement(By.cssSelector(".field:nth-child(2) .input")).click();
    // 6 | type | css=.field:nth-child(2) .input | Da12345*
    driver.findElement(By.cssSelector(".field:nth-child(2) .input")).sendKeys("Da12345*");
    // 7 | click | css=.button | 
    driver.findElement(By.cssSelector(".button")).click();
    // 8 | click | linkText=Registro | 
    driver.findElement(By.linkText("Registro")).click();
    // 9 | click | linkText=Periodo | 
    driver.findElement(By.linkText("Periodo")).click();
    // 10 | click | css=tr:nth-child(2) .input | 
    driver.findElement(By.cssSelector("tr:nth-child(2) .input")).click();
    // 11 | type | css=tr:nth-child(2) .input | 2024-1
    driver.findElement(By.cssSelector("tr:nth-child(2) .input")).sendKeys("2024-1");
    // 12 | click | css=tr:nth-child(3) .input | 
    driver.findElement(By.cssSelector("tr:nth-child(3) .input")).click();
    // 13 | type | css=tr:nth-child(3) .input | Inactivo
    driver.findElement(By.cssSelector("tr:nth-child(3) .input")).sendKeys("Inactivo");
    // 14 | click | css=.is-success | 
    driver.findElement(By.cssSelector(".is-success")).click();
    // 15 | click | css=tr:nth-child(2) .is-warning .fas | 
    driver.findElement(By.cssSelector("tr:nth-child(2) .is-warning .fas")).click();
    // 16 | click | css=tbody > tr:nth-child(2) | 
    driver.findElement(By.cssSelector("tbody > tr:nth-child(2)")).click();
    // 17 | type | css=td:nth-child(3) > .input | Activo
    driver.findElement(By.cssSelector("td:nth-child(3) > .input")).sendKeys("Activo");
    // 18 | click | css=.fa-check | 
    driver.findElement(By.cssSelector(".fa-check")).click();
    // 19 | click | css=tr:nth-child(2) .is-danger .fas | 
    driver.findElement(By.cssSelector("tr:nth-child(2) .is-danger .fas")).click();
    // 20 | click | css=.p-confirm-dialog-accept > .p-button-label | 
    driver.findElement(By.cssSelector(".p-confirm-dialog-accept > .p-button-label")).click();
    // 21 | click | css=.navbar-item > .button | 
    driver.findElement(By.cssSelector(".navbar-item > .button")).click();
  }
}
