// Generated by Selenium IDE
package pe.edu.upeu;

import java.time.Duration;
import org.junit.jupiter.api.Test;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.Keys;

public class SysEventosTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    Utilx u = new Utilx();

    @BeforeEach
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", u.getFile("chromedriver.exe").getAbsolutePath());
        //System.setProperty("webdriver.chrome.driver", "D:\\SOFT-TESTING\\DRIVER\\chromedriver.exe");
        //ChromeOptions opt = new ChromeOptions();
        //opt.addArguments("--incognito");

        //opt.setLocalState(new HashMap<String, Object>());
        driver = new ChromeDriver();
        String token = "mi_token";
        //driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterEach
    public void tearDown() {
        // driver.quit();
    }

    @Test
    public void sysEventos() {
        // Test name: SysEventos
        // Step # | name | target | value
        // 1 | open | / | 
        driver.get("http://localhost:8080/");
        // 2 | setWindowSize | 1552x840 | 
        driver.manage().window().setSize(new Dimension(1552, 840));
        // 3 | click | css=.field:nth-child(1) .input | 
        driver.findElement(By.cssSelector(".field:nth-child(1) .input")).click();
        // 4 | type | css=.field:nth-child(1) .input | davidmp@upeu.edu.pe
        driver.findElement(By.cssSelector(".field:nth-child(1) .input")).sendKeys("davidmp@upeu.edu.pe");
        // 5 | click | css=.field:nth-child(2) .input | 
        driver.findElement(By.cssSelector(".field:nth-child(2) .input")).click();
        // 6 | type | css=.field:nth-child(2) .input | Da12345*
        driver.findElement(By.cssSelector(".field:nth-child(2) .input")).sendKeys("Da12345*");
        // 7 | click | css=.button | 
        driver.findElement(By.cssSelector(".button")).sendKeys(Keys.ENTER);

        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(60));
        // 8 | click | linkText=Periodo |         
        driver.findElement(By.linkText("Registro")).click();
        driver.findElement(By.linkText("Periodo")).click();
        // 9 | click | css=tr:nth-child(2) .input | 
        driver.findElement(By.cssSelector("tr:nth-child(2) .input")).click();
        // 10 | type | css=tr:nth-child(2) .input | 2024-1
        driver.findElement(By.cssSelector("tr:nth-child(2) .input")).sendKeys("2024-1");
        // 11 | click | css=tr:nth-child(3) .input | 
        driver.findElement(By.cssSelector("tr:nth-child(3) .input")).click();
        // 12 | click | css=tr:nth-child(3) .input | 
        driver.findElement(By.cssSelector("tr:nth-child(3) .input")).click();
        // 13 | type | css=tr:nth-child(3) .input | Inactivo
        driver.findElement(By.cssSelector("tr:nth-child(3) .input")).sendKeys("Inactivo");
        // 14 | click | css=.is-success | 
        driver.findElement(By.cssSelector(".is-success")).click();
        // 15 | mouseOver | css=.is-success | 
        {
            WebElement element = driver.findElement(By.cssSelector(".is-success"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 16 | mouseOut | css=.is-success | 
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        // 17 | click | css=tr:nth-child(3) > td:nth-child(3) | 
        driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3)")).click();
        // 18 | click | css=tbody > tr:nth-child(3) > td:nth-child(2) | 
        driver.findElement(By.cssSelector("tbody > tr:nth-child(3) > td:nth-child(2)")).click();
        // 19 | click | css=tbody > tr:nth-child(3) > td:nth-child(2) | 
        driver.findElement(By.cssSelector("tbody > tr:nth-child(3) > td:nth-child(2)")).click();
        // 20 | doubleClick | css=tbody > tr:nth-child(3) > td:nth-child(2) | 
        {
            WebElement element = driver.findElement(By.cssSelector("tbody > tr:nth-child(3) > td:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        // 21 | click | css=.pagination-list | 
        driver.findElement(By.cssSelector(".pagination-list")).click();
        // 22 | click | css=tr:nth-child(3) .is-warning .fas | 
        driver.findElement(By.cssSelector("tr:nth-child(3) .is-warning .fas")).click();
        // 23 | click | css=tbody > tr:nth-child(3) | 
        driver.findElement(By.cssSelector("tbody > tr:nth-child(3)")).click();
        // 24 | type | css=td:nth-child(3) > .input | Activo
        driver.findElement(By.cssSelector("td:nth-child(3) > .input")).sendKeys("Activo");
        // 25 | click | css=.fa-check | 
        driver.findElement(By.cssSelector(".fa-check")).click();
        // 26 | click | css=tr:nth-child(3) > td:nth-child(3) | 
        driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3)")).click();
        // 27 | click | css=tr:nth-child(3) > td:nth-child(3) | 
        driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3)")).click();
        // 28 | doubleClick | css=tr:nth-child(3) > td:nth-child(3) | 
        {
            WebElement element = driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3)"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        // 29 | click | css=html | 
        driver.findElement(By.cssSelector("html")).click();
        // 30 | click | css=tr:nth-child(3) .is-danger > .icon | 
        driver.findElement(By.cssSelector("tr:nth-child(3) .is-danger > .icon")).click();
        // 31 | click | css=.p-confirm-dialog-accept > .p-button-label | 
        driver.findElement(By.cssSelector(".p-confirm-dialog-accept > .p-button-label")).click();
        // 32 | click | css=.columns | 
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(60));
        System.out.println("Llegoxx");
        //driver.findElement(By.cssSelector(".columns")).click();
        // 33 | click | css=.navbar-item > .button | 
        //driver.findElement(By.cssSelector(".navbar-item > .button")).click();
        driver.findElement(By.xpath("/html/body/div/div/div/nav/div[2]/div[2]/div/button")).sendKeys(Keys.ENTER);
        //boolean contains = driver.findElement(By.xpath("/html/body/div/div/div/nav/div[2]/div[2]/div/button")).getText().contains("Cerrar");
        //System.out.println("Rsul:" + contains);
        // 34 | click | css=.hero-body |
        // driver.findElement(By.cssSelector(".hero-body")).click();
    }
}
